# Generated by Django 5.0.1 on 2024-01-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('medicine', models.CharField(max_length=200, unique=True)),
                ('price', models.IntegerField(verbose_name='Price for the medicine')),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
